// <auto-generated />
using System;
using ElectroShop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectroShop.Migrations
{
    [DbContext(typeof(ElectroShopContext))]
    partial class ElectroShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectroShop.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4831c"),
                            Description = "Heladeras"
                        },
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4832c"),
                            Description = "Notebooks"
                        },
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4833c"),
                            Description = "Celulares"
                        },
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4834c"),
                            Description = "Mouses"
                        },
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4835c"),
                            Description = "Teclados"
                        },
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4836c"),
                            Description = "Auriculares"
                        },
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4837c"),
                            Description = "Tablets"
                        },
                        new
                        {
                            CategoryId = new Guid("b3a3096e-4274-4799-a843-380868d4838c"),
                            Description = "TVs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
